const products=[
{id:'blazer',name:'Tailored Blazer',price:189,fit:'cover',sizes:['XS','S','M','L'],variants:[{name:'Black',hex:'#111',img:'./assets/products/tailored-blazer.webp'},{name:'Ivory',hex:'#eee8dc',img:'./assets/products/colors/blazer-ivory.webp'}],description:'A sharply tailored blazer with clean architectural lines, a softly structured shoulder and a refined wool-blend finish.'},
{id:'tote',name:'Leather Tote Bag',price:159,fit:'contain',sizes:[],variants:[{name:'Black',hex:'#111',img:'./assets/products/leather-tote.webp'},{name:'Ivory',hex:'#eee9df',img:'./assets/products/colors/tote-ivory.webp'}],description:'A minimalist everyday tote crafted in smooth leather with a spacious interior and understated structure.'},
{id:'dress',name:'Silk Slip Dress',price:129,fit:'cover',sizes:['XS','S','M','L'],variants:[{name:'Black',hex:'#111',img:'./assets/products/silk-slip-dress.webp'},{name:'Ivory',hex:'#f0ebe2',img:'./assets/products/colors/dress-ivory.webp'}],description:'A fluid slip dress with a soft sheen, delicate straps and a clean elongated silhouette.'},
{id:'shirt',name:'Oversized Shirt',price:89,fit:'contain',sizes:['XS','S','M','L'],variants:[{name:'White',hex:'#f3f0e9',img:'./assets/products/oversized-shirt.webp'},{name:'Black',hex:'#111',img:'./assets/products/colors/shirt-black.webp'}],description:'A relaxed oversized shirt cut from crisp cotton with dropped shoulders and precise cuffs.'},
{id:'trousers',name:'Wide Leg Trousers',price:119,fit:'cover',sizes:['XS','S','M','L'],variants:[{name:'Black',hex:'#111',img:'./assets/products/wide-leg-trousers.webp'},{name:'Ivory',hex:'#efebe2',img:'./assets/products/colors/trousers-ivory.webp'}],description:'High-rise trousers with a fluid wide leg and clean front construction.'},
{id:'belt',name:'Leather Belt',price:49,fit:'contain',sizes:['70','75','80','85'],variants:[{name:'Black',hex:'#111',img:'./assets/products/leather-belt.webp'},{name:'Ivory',hex:'#f1ece2',img:'./assets/products/colors/belt-ivory.webp'}],description:'A slim leather belt finished with a minimal metal buckle.'},
{id:'heels',name:'Leather Slingbacks',price:169,fit:'contain',sizes:['36','37','38','39','40'],variants:[{name:'Black',hex:'#111',img:'./assets/products/slingbacks.webp'},{name:'Ivory',hex:'#f0ebe2',img:'./assets/products/colors/heels-ivory.webp'}],description:'Refined leather slingbacks with a pointed toe and balanced low heel.'},
{id:'scarf',name:'Silk Scarf',price:59,fit:'contain',sizes:[],variants:[{name:'Black',hex:'#111',img:'./assets/products/silk-scarf.webp'},{name:'Ivory',hex:'#f3eee5',img:'./assets/products/colors/scarf-ivory.webp'}],description:'A lightweight silk scarf with a restrained tonal design.'},
{id:'shoulder',name:'Minimal Shoulder Bag',price:139,fit:'contain',sizes:[],variants:[{name:'Black',hex:'#111',img:'./assets/products/shoulder-bag.webp'},{name:'Ivory',hex:'#efeae1',img:'./assets/products/colors/shoulder-ivory.webp'}],description:'A compact shoulder bag with a softly curved profile and clean hardware.'},
{id:'earrings',name:'Sculptural Earrings',price:39,fit:'contain',sizes:[],variants:[{name:'Silver',hex:'#c7c7c7',img:'./assets/products/silver-earrings.webp'},{name:'Gold',hex:'#c6a15b',img:'./assets/products/colors/earrings-gold.webp'}],description:'Sculptural earrings with a polished finish.'}
];
const qs=s=>document.querySelector(s),money=n=>`$${n.toFixed(2)}`,id=new URLSearchParams(location.search).get('id')||'blazer',p=products.find(x=>x.id===id)||products[0];let state={color:p.variants[0].name,image:p.variants[0].img,size:p.sizes[0]||''};
qs('[data-pd-name]').textContent=p.name;qs('[data-pd-price]').textContent=money(p.price);qs('[data-pd-description]').textContent=p.description;document.title=`SORA — ${p.name}`;
const image=qs('[data-pd-image]');image.src=state.image;image.alt=p.name;image.style.objectFit=p.fit==='contain'?'contain':'cover';qs('[data-pd-image-second]').src=p.variants[1]?.img||p.variants[0].img;qs('[data-pd-image-second]').style.objectFit=p.fit==='contain'?'contain':'cover';
const colors=qs('[data-pd-colors]');colors.innerHTML=p.variants.map((v,i)=>`<button class="quick-color${i===0?' is-active':''}" data-index="${i}"><i style="background:${v.hex}"></i><span>${v.name}</span></button>`).join('');qs('[data-pd-selected]').textContent=`Selected: ${state.color}`;colors.querySelectorAll('button').forEach(b=>b.onclick=()=>{const v=p.variants[+b.dataset.index];state.color=v.name;state.image=v.img;image.src=v.img;colors.querySelectorAll('button').forEach(x=>x.classList.toggle('is-active',x===b));qs('[data-pd-selected]').textContent=`Selected: ${v.name}`});
const sizeWrap=qs('[data-pd-size-wrap]'),sizes=qs('[data-pd-sizes]');sizeWrap.hidden=!p.sizes.length;sizes.innerHTML=p.sizes.map((s,i)=>`<button class="quick-size${i===0?' is-active':''}" data-size="${s}">${s}</button>`).join('');sizes.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.size=b.dataset.size;sizes.querySelectorAll('button').forEach(x=>x.classList.toggle('is-active',x===b));qs('[data-pd-size-selected]').textContent=`Selected: ${state.size}`});
qs('[data-pd-add]').onclick=()=>{let cart=[];try{cart=JSON.parse(localStorage.getItem('sora-cart'))||[]}catch{}const item=cart.find(x=>x.id===p.id&&x.color===state.color&&x.size===state.size);item?item.qty++:cart.push({id:p.id,qty:1,color:state.color,image:state.image,size:state.size});localStorage.setItem('sora-cart',JSON.stringify(cart));const t=qs('[data-toast]');t.textContent='Added to bag';t.classList.add('is-visible');setTimeout(()=>t.classList.remove('is-visible'),1600)};
